<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SoundSnack</title>
    <link rel="stylesheet" href="app/css/homeStyle.css">
    <link rel="stylesheet" href="app/css/formStyle.css">
    <link rel="stylesheet" href="app/css/adminStyle.css">
</head>

<body>
    <header>
        <div class="header-container">
            <div class="site-title">
                <h1><a href="home">SoundSnack</a></h1>
                <h2>Tu música, a un clic</h2>
            </div>

            <div class="user-info">
                <?php if ($user): ?>
                    <!-- Si la sesión se encuentra activa -->
                    <div class="user-details">
                        <p class="username"><?= isset($user['name']) ? htmlspecialchars($user['name']) : 'Usuario' ?></p>
                        <img class="profile-pic"
                            src="<?= isset($user['profilePhoto']) && !empty($user['profilePhoto']) ? htmlspecialchars($user['profilePhoto']) : 'assets/img/covers/users/default.jpg' ?>"
                            alt="Foto de perfil" />
                        <p class="email"><?= isset($user['email']) ? htmlspecialchars($user['email']) : '' ?></p>
                        <button class="btn-logout"><a href="logOut">Cerrar sesión</a></button>
                    </div>
                <?php else: ?>
                    <!-- Si la sesión no se encuentra activa -->
                    <div class="user-details">
                        <p class="username">Guest4821</p>
                        <img class="profile-pic" src="assets/img/covers/users/default.jpg" alt="Foto de perfil genérica" />
                        <p class="email">guest4821@example.com</p>
                        <button class="btn-login"><a href="login">Iniciar sesión</a></button>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </header>