  <section>
            <div>
                <h3>Registro de usuario nuevo</h3>
            </div>
            <form id="userRegistration" action="registerUser" method="post" enctype="multipart/form-data">
                <div id="posDiv">
                    <div>
                        <label for="userName">Nombre de usuario
                            <input name = "userName" type="text" placeholder="Nombre de usuario" minlength="8" required>
                        </label>
                    </div>

                    <div>
                        <label for="userEmail">Correo electrónico
                            <input name = "userEmail" type="email" placeholder="Correo elecrónico" required>
                        </label>
                    </div>
                </div>

                <div id="posDiv">

                    <div>
                        <label for="userPassword">Contraseña
                            <input name = "userPassword" type="password" placeholder="Contraseña" minlength = 8 required>
                        </label>
                    </div>

                    <div>
                        <label for="photoUser">Foto de perfil (opcional)
                            <input name = "photoUser" id="file" type="file">
                        </label>
                    </div>
                </div>

                <div><button type="submit">Enviar</button></div>
            </form>
        </section>