<article class="admin-info">
    <h1>Administración de bases de datos</h1>
    <p>
        El personal autorizado para realizar tareas administrativas en la base de datos deberá ser
        responsable de asegurar la correcta manipulación de los datos del sitio con el propósito de garantizar su
        legibilidad y evitar futuros inconvenientes. La <strong>incorrecta manipulación de los datos</strong> del sitio puede
        llevar al personal a recibir duras sanciones por parte del cuerpo superior de la empresa. Por lo tanto,
        se recomienda al personal autorizado a prestar mucha atención a la funcionalidad que ofrece cada uno de los
        formularios y sus requerimientos. <strong>¡Saludos!</strong>
    </p>