<nav class="main-nav">
    <ul class="nav-list">
        <li class="nav-item">
            <a href="/soundSnack/admin/#adminArtists" class="nav-link">Artistas</a>
        </li>
        <li class="nav-item">
            <a href="/soundSnack/admin/#adminSongs" class="nav-link">Canciones</a>
        </li>
        <li class="nav-item">
            <a href="/soundSnack/admin/#adminUsers" class="nav-link">Usuarios</a>
        </li>
    </ul>
</nav>