<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>500 - Internal Server Error</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body class="bg-dark text-light d-flex align-items-center justify-content-center vh-100">
    <div class="text-center p-5 rounded bg-secondary shadow-lg">
        <h1 class="display-1 text-danger fw-bold">500</h1>
        <p class="fs-4">Internal Server Error.<br>Please try again later.</p>
        <a href="home" class="btn btn-danger btn-lg mt-3">Go to Home</a>
    </div>
</body>

</html>