<?php require './app/templates/header.phtml' ?>

<h4>Sobre la Pelicula</h4>
<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <h5><?= $movie->title ?></h5>
            <p>Director: <?= $movie->director ?></p>
            <p>Año de Estreno: <?= $movie->release_date ?></p>
            <p>Duracion: <?= $movie->runtime ?></p>
            <p>Genero: <?= $movie->genre ?></p>
            <p>Sinopsis: <?= $movie->synopsis ?></p>
        </div>
    </li>
</ul>

<?php require './app/templates/footer.phtml' ?>