<form action="movies-save/<?= $movie->id_movie ?>" method="POST">

    <div class="row">
        <!-- TODO -->
        <!-- Poner como atributo value="<?= $movie->atributo ?>" -->
        <!-- Poner los atributos REQUIRED NAME -->

        <label>Titulo</label>
        <input type="text" placeholder="Titulo">

        <label>Director</label>
        <input type="text" placeholder="Director/es">

        <label>Año de Estreno</label>
        <input type="number" placeholder="AÑO">

        <label>Duracion</label>
        <input type="number" placeholder="en MINUTOS">

        <label>Genero</label>
        <input type="text" placeholder="Genero/s">

        <label>Sinopsis</label>
        <textarea required name="body" placeholder="Ingrese el año" class="form-control" rows="4" cols="50"></textarea>

    </div>

    <button type="submit" class="btn btn-primary mt-2">Editar</button>
</form>