<div>
        <label>Artista</label>
        <select required name="id_artist">
            <option selected disabled>De que artista es la canción?</option>
            <?php foreach ($artists as $artist) : ?>
                <option value="<?= $artist->id_artist ?>"><?= $artist->name ?></option>
            <?php endforeach ?>
        </select>

        <label for="title">Título</label>
        <input required name="title" type="text" id="title" value="<?= $song->title ?>">

        <label for="album">Álbum</label>
        <input required name="album" type="text" id="album" value="<?= $song->album ?>">

        <label for="duration">Duración</label>
        <input required name="duration" type="number" id="duration" value="<?= $song->duration ?>">

        <label for="genre">Género</label>
        <input required name="genre" type="text" id="genre" value="<?= $song->genre ?>">

        <label for="video">Link al Video</label>
        <input required name="video" type="text" id="video" value="<?= $song->video ?>">
    </div>