<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">

    <!-- Conexion al Bootstrap -->

    <title>Reviews de Peliculas</title>
</head>

<body>
    <!-- HEADER -->
    <header>
        <!-- Navigation -->
        <nav>
            <ul>
                <!-- Acceso Publico -->
                <li> <a href="">Reseñas</a></li>
                <li> <a href="">Peliculas</a></li>

                <!-- Acceso admin de datos -->
                <?php if ($this->session) : ?>
                    <li>
                        <a href="logout">Logout (<?= $_SESSION['USER_NAME'] ?>)</a>
                    </li>
                <?php else : ?>
                    <li>
                        <a href="login">Login</a>
                    </li>
                <?php endif ?>
            </ul>

        </nav>
    </header>