<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">

    <!-- link href posible bootstrap? -->

    <title>SoundSnack</title>
</head>

<body>
    <!-- HEADER -->
    <header>

        <!-- NAV -->
        <nav>

            <!-- Public Access -->
            <li><a href="songs">Canciones</a></li>
            <li><a href="artists">Artistas</a></li>

            <!-- Admin Access -->
            <?php if ($this->session) : ?>
                <li class="nav-item">
                    <a class="nav-link" href="logout">Logout (<?= $_SESSION['USER_NAME'] ?>)</a>
                </li>
            <?php else : ?>
                <li class="nav-item">
                    <a class="nav-link" href="login">Login</a>
                </li>
            <?php endif; ?>
        </nav>

    </header>
</body>