<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<!-- songList.phtml -->
<h1>SongList</h1>

<table cellpadding="8" cellspacing="0">

    <thead>
        <tr>
            <th>Canción</th>
            <th>Artista</th>
            <th>Álbum</th>
            <th>Duración</th>
            
            <!-- ABM ACCIONES -->
            <?php //if ($this->session) : ?>
            <th>Acciones</th>
            <?php //endif; ?>

        </tr>
    </thead>

    <tbody>
        <?php if (!empty($songs)): ?>

            <?php foreach ($songs as $song): ?>
                <tr>
                    <!-- songDetail -->
                    <td><a href="songs/<?= $song->id_song ?>"><?= $song->title ?></a></td>

                    <!--  artistDetail  -->
                    <td><a href="artists/<?= $song->id_artist ?>"><?= htmlspecialchars($song->name) ?></a></td>

                    <td><?= $song->album ?></td>
                    <td><?= $song->duration ?></td>

                    <!-- SI ESTA ACTIVA LA SESSION MOSTRAR BOTONES DE ABM -->
                    <?php //if ($this->session) : ?>
                        <td>
                            <a href="editSong/<?= $song->id_song ?> " class="btn btn-primary">Editar</a>
                            <a href="removeSong/<?= $song->id_song ?>" class="btn btn-danger"
                                onclick="return confirm('¿Estás seguro de que queres borrar esta canción?');">Borrar</a>
                        </td>
                    <?php //endif ?>

                </tr>
            <?php endforeach; ?>

        <?php else: ?>
            <tr>
                <td>No hay canciones para mostrar.</td>
            </tr>
        <?php endif; ?>
    </tbody>
    
</table>

<?php require './app/templates/footer.phtml' ?>