<?php require './app/templates/header.phtml' ?>

<!-- TIRA ERROR PORQUE ESTA NULL. Attempt to read property -->
<!-- por QUÉ está null ??? -->

<div>
    <h4><?= $song->title ?></h4>
    <h5><a href="artists/<?= $song->id_artist ?>"><?= htmlspecialchars($song->name) ?></a></h5>
    <p><?= $song->album ?></p>
    <p><?= $song->duration ?></p>
    <p><?= $song->genre ?></p>
    <p><?= $song->video ?></p>
</div>

<?php require './app/templates/footer.phtml' ?>